const shows=[
 ['Провожающая в последний путь Фрирен','8 серия','9.1','https://cdn.myanimelist.net/images/anime/1015/138006.jpg'],['Монолог фармацевта','18 серия','8.8','https://cdn.myanimelist.net/images/anime/1708/138033.jpg'],['Поднятие уровня в одиночку','12 серия','8.6','https://cdn.myanimelist.net/images/anime/1823/142156.jpg'],['Атака титанов','87 серия','9.0','https://cdn.myanimelist.net/images/anime/10/47347.jpg'],['Магическая битва','23 серия','8.7','https://cdn.myanimelist.net/images/anime/1171/109222.jpg'],['Человек-бензопила','12 серия','8.5','https://cdn.myanimelist.net/images/anime/1806/126216.jpg'],['Ванпанчмен','24 серия','8.6','https://cdn.myanimelist.net/images/anime/12/76049.jpg'],['Созданный в Бездне','12 серия','8.8','https://cdn.myanimelist.net/images/anime/6/86733.jpg'],['Киберпанк: Бегущие по краю','10 серия','8.7','https://cdn.myanimelist.net/images/anime/1818/126435.jpg'],['Семья шпиона','25 серия','8.4','https://cdn.myanimelist.net/images/anime/1441/122795.jpg'],['Звёздное дитя','11 серия','8.4','https://cdn.myanimelist.net/images/anime/1812/134736.jpg'],['Блич: Тысячелетняя война','26 серия','8.5','https://cdn.myanimelist.net/images/anime/1908/135431.jpg']
];
const url=src=>src;
function card(s){return `<article class="card" data-view="anime"><div class="poster"><img src="${url(s[3])}" alt="${s[0]}"><span class="rating-badge">★ ${s[2]}</span></div><h3>${s[0]}</h3><p>${s[1]} <b>★ ${s[2]}</b></p></article>`}
function render(){document.querySelector('#popularRow').innerHTML=shows.slice(0,6).map(card).join('');document.querySelector('#newRow').innerHTML=shows.slice(6,12).map(card).join('');document.querySelector('#recommendRow').innerHTML=shows.slice(3,9).map(card).join('');document.querySelector('#similarRow').innerHTML=shows.slice(1,7).map(card).join('');document.querySelector('#catalogGrid').innerHTML=shows.concat(shows.slice(0,6)).map(card).join('');document.querySelector('#continueRow').innerHTML=shows.slice(0,3).map((s,i)=>`<article class="continue-card" data-view="watch"><img src="${url(s[3])}" alt=""><div><h3>${s[0]}</h3><p>Продолжить с ${8-i*2} серии · ${['14:32','07:09','20:48'][i]}</p><div class="mini-progress"><i style="width:${[61,29,84][i]}%"></i></div></div></article>`).join('')}
const titles=['Конец путешествия','Не обязательно было знать','Убийство волшебников','Земля, где покоятся души','Призраки мёртвых','Герой южных земель','Как сказка','В стране смертных','Аура, убийца','Сильный маг','Зима в северных землях','Настоящий герой'];
function episodes(){const html=titles.map((t,i)=>`<button class="episode ${i===7?'active':''}" data-ep="${i+1}"><span class="num">${String(i+1).padStart(2,'0')}</span><span>${t}<small>24 мин.</small></span></button>`).join('');document.querySelector('#episodeList').innerHTML=html;document.querySelector('#detailEpisodes').innerHTML=titles.map((t,i)=>`<button class="${i===7?'active':''}" data-view="watch"><b>${String(i+1).padStart(2,'0')}. ${t}</b><small>24 мин.</small></button>`).join('')}
function setView(name){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.main-nav a').forEach(x=>x.classList.toggle('active',x.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){e.preventDefault();setView(v.dataset.view)}const ep=e.target.closest('.episode');if(ep){document.querySelectorAll('.episode').forEach(x=>x.classList.remove('active'));ep.classList.add('active');document.querySelector('#currentEpisode').textContent=ep.dataset.ep;document.querySelector('.watch-title h2').textContent=`${ep.dataset.ep.padStart(2,'0')}. ${titles[ep.dataset.ep-1]}`}});
let playing=false;function togglePlay(){playing=!playing;document.querySelector('#playButton').textContent=playing?'Ⅱ':'▶';document.querySelector('#controlPlay').textContent=playing?'Ⅱ':'▶'}document.querySelector('#playButton').onclick=togglePlay;document.querySelector('#controlPlay').onclick=togglePlay;document.querySelector('#nextEpisode').onclick=()=>{let x=document.querySelector('.episode.active'),n=x.nextElementSibling;if(n)n.click()};
function fav(e){e.currentTarget.classList.toggle('selected');e.currentTarget.textContent=e.currentTarget.classList.contains('selected')?'♥ В избранном':'♡ В избранное';const t=document.querySelector('#toast');t.textContent=e.currentTarget.classList.contains('selected')?'Добавлено в избранное':'Удалено из избранного';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}document.querySelector('#favoriteButton').onclick=fav;document.querySelector('#animeFavorite').onclick=fav;
const overlay=document.querySelector('#searchOverlay'),input=document.querySelector('#searchInput');document.querySelector('#searchToggle').onclick=()=>{overlay.classList.add('open');input.focus()};document.addEventListener('keydown',e=>{if(e.key==='Escape')overlay.classList.remove('open')});input.oninput=()=>{let q=input.value.toLowerCase();document.querySelector('#quickResults').innerHTML=shows.filter(x=>x[0].toLowerCase().includes(q)).slice(0,4).map(s=>`<div class="quick-result" data-view="anime"><img src="${url(s[3])}"><div><b>${s[0]}</b><span>${s[1]} · ★ ${s[2]}</span></div></div>`).join('')};document.querySelector('#catalogSearch').oninput=e=>document.querySelector('#catalogGrid').innerHTML=shows.filter(x=>x[0].toLowerCase().includes(e.target.value.toLowerCase())).map(card).join('');render();episodes();

const frierenKeyVisual='https://times-abema.ismcdn.jp/mwimgs/9/b/1448w/img_9b186644b5996f24880640af7697883e4062853.jpg';
document.querySelector('.hero-backdrop').style.backgroundImage=`url('${frierenKeyVisual}')`;
document.querySelector('.hero-progress img').src=shows[0][3];
document.querySelector('.hero-progress img').alt='Официальный постер Фрирен';
document.querySelector('.player > img').src=frierenKeyVisual;
document.querySelector('.player > img').alt='Официальный постер аниме Фрирен';
document.querySelector('.anime-cover img').src=shows[0][3];
document.querySelector('.anime-cover img').alt='Официальный постер Фрирен';

document.head.insertAdjacentHTML('beforeend', `<style>
.poster{isolation:isolate}.poster .rating-badge{position:absolute;top:9px;right:9px;z-index:2;background:#101116e8;border:1px solid #ffffff1f;color:#f6d36c;padding:6px 8px;border-radius:7px;font-size:11px;font-weight:700;opacity:0;transform:translateY(-5px);transition:opacity .2s,transform .2s}.card:hover .rating-badge{opacity:1;transform:none}.comments{margin-top:16px;border-top:1px solid var(--line);padding:16px 14px}.comments h4{font:700 14px Manrope;margin:0 0 13px}.comment-list{display:grid;gap:12px;max-height:170px;overflow:auto;padding-right:2px}.comment{font-size:11px;line-height:1.45;color:#c4c5cb}.comment b{display:block;color:#f0f0f2;font-size:11px;margin-bottom:3px}.comment time{color:#777985;font-weight:400;margin-left:5px}.comment-form{display:flex;gap:7px;margin-top:13px}.comment-form input{min-width:0;flex:1;background:#202126;border:1px solid #303139;border-radius:8px;color:#fff;outline:0;padding:9px 10px;font:11px Inter}.comment-form input:focus{border-color:#7561cb}.comment-form button{background:var(--accent);border:0;border-radius:8px;color:#fff;padding:0 10px;font-size:12px;cursor:pointer}.comments .login-note{font-size:10px;color:#858690;margin:8px 0 0}
</style>`);
document.querySelector('.episodes').insertAdjacentHTML('beforeend', `<section class="comments"><h4>Комментарии <span>· 124</span></h4><div class="comment-list"><article class="comment"><b>Rin <time>12 мин.</time></b>Очень спокойная серия, музыка — просто чудо.</article><article class="comment"><b>Kenji <time>38 мин.</time></b>Фрирен в этом эпизоде невероятна.</article></div><form class="comment-form" id="commentForm"><input id="commentInput" maxlength="180" placeholder="Напишите комментарий…"><button type="submit">↑</button></form><p class="login-note">Ваш комментарий увидят другие зрители.</p></section>`);
document.querySelector('#commentForm').addEventListener('submit', event=>{event.preventDefault();const input=document.querySelector('#commentInput'),text=input.value.trim();if(!text)return;document.querySelector('.comment-list').insertAdjacentHTML('afterbegin',`<article class="comment"><b>Вы <time>сейчас</time></b>${text.replace(/[<>&]/g, char=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[char]))}</article>`);input.value='';const toast=document.querySelector('#toast');toast.textContent='Комментарий опубликован';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)});

document.head.insertAdjacentHTML('beforeend', `<style>
.forum-link{opacity:.52;cursor:not-allowed!important}.auth-modal{position:fixed;inset:0;z-index:30;background:#090a0ab8;display:none;place-items:center;padding:18px}.auth-modal.open{display:grid}.auth-card{width:min(100%,390px);background:#17181c;border:1px solid #34353d;border-radius:15px;padding:25px;box-shadow:0 24px 70px #0008}.auth-card h2{font:700 24px Manrope;margin:0 0 7px}.auth-card>p{color:#999ba5;margin:0 0 20px;font-size:12px}.auth-card label{display:block;color:#c4c5ca;font-size:11px;margin:12px 0 6px}.auth-card input{width:100%;background:#202126;border:1px solid #32333b;border-radius:9px;padding:11px;color:#fff;outline:none;font:13px Inter}.auth-card input:focus{border-color:#8069dd}.auth-card .primary{width:100%;margin-top:18px}.auth-close{float:right;background:transparent;border:0;color:#999;font-size:20px;cursor:pointer}.auth-hint{font-size:10px!important;line-height:1.5}.profile{cursor:pointer}
</style>`);
document.querySelector('.main-nav').insertAdjacentHTML('beforeend','<a class="forum-link" title="Форум скоро появится">Форум · скоро</a>');
document.body.insertAdjacentHTML('beforeend', `<div class="auth-modal" id="authModal" role="dialog" aria-modal="true"><form class="auth-card" id="authForm"><button type="button" class="auth-close" id="authClose">×</button><h2 id="authTitle">Создать профиль</h2><p id="authDescription">Сохраняйте избранное, историю и комментарии.</p><label class="auth-name-field" for="authName">Имя</label><input class="auth-name-field" id="authName" maxlength="24" placeholder="Например, Akira"><label for="authEmail">Email</label><input id="authEmail" type="email" required placeholder="you@example.com"><label for="authPassword">Пароль</label><input id="authPassword" type="password" required minlength="6" placeholder="Минимум 6 символов"><p id="authError" class="auth-hint" aria-live="polite"></p><button class="primary" id="authSubmit" type="submit">Зарегистрироваться</button><button class="auth-switch" id="authSwitch" type="button">Уже есть аккаунт? Войти</button></form></div>`);
const profileButton=document.querySelector('.profile'),authModal=document.querySelector('#authModal'),authClient=window.supabase.createClient('https://bgurzxyjlkpqvyvkbbwa.supabase.co','sb_publishable_2UXHGppppB7B5WkUAASeCg_2WYXGjU0');let authMode='signup';
function toastMessage(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function setProfile(user){const name=user?.user_metadata?.name||user?.email?.split('@')[0]||'Профиль',avatar=user?.user_metadata?.avatar||'';profileButton.textContent='';profileButton.classList.toggle('has-avatar',Boolean(avatar));if(avatar){const image=document.createElement('img');image.src=avatar;image.alt=name;profileButton.append(image)}else profileButton.textContent=name.slice(0,2).toUpperCase();profileButton.title=name;profileButton.dataset.loggedIn=Boolean(user)}
function setAuthMode(mode){authMode=mode;const isSignup=mode==='signup';document.querySelector('#authTitle').textContent=isSignup?'Создать профиль':'Войти в Hikari';document.querySelector('#authDescription').textContent=isSignup?'Сохраняйте избранное, историю и комментарии.':'Продолжите просмотр с того же места.';document.querySelectorAll('.auth-name-field').forEach(x=>x.style.display=isSignup?'block':'none');document.querySelector('#authName').required=isSignup;document.querySelector('#authSubmit').textContent=isSignup?'Зарегистрироваться':'Войти';document.querySelector('#authSwitch').textContent=isSignup?'Уже есть аккаунт? Войти':'Нет аккаунта? Зарегистрироваться';document.querySelector('#authError').textContent=''}
authClient.auth.getSession().then(({data:{session}})=>setProfile(session?.user));authClient.auth.onAuthStateChange((_event,session)=>setProfile(session?.user));
profileButton.addEventListener('click',()=>{if(profileButton.dataset.loggedIn==='true'){setView('profile');authClient.auth.getUser().then(({data:{user}})=>fillProfilePage(user))}else{setAuthMode('signup');authModal.classList.add('open')}});
document.querySelector('#authClose').onclick=()=>authModal.classList.remove('open');document.querySelector('#authSwitch').onclick=()=>setAuthMode(authMode==='signup'?'signin':'signup');authModal.addEventListener('click',event=>{if(event.target===authModal)authModal.classList.remove('open')});
document.querySelector('#authForm').addEventListener('submit',async event=>{event.preventDefault();const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value,name=document.querySelector('#authName').value.trim(),errorBox=document.querySelector('#authError'),submit=document.querySelector('#authSubmit');errorBox.textContent='';submit.disabled=true;submit.textContent='Подождите…';let result;if(authMode==='signup'){result=await authClient.auth.signUp({email,password,options:{data:{name},emailRedirectTo:'https://harmas01.github.io/hikari/'}})}else{result=await authClient.auth.signInWithPassword({email,password})}submit.disabled=false;submit.textContent=authMode==='signup'?'Зарегистрироваться':'Войти';if(result.error){errorBox.textContent=result.error.message;return}if(authMode==='signup'&&!result.data.session){errorBox.textContent='Проверьте почту: мы отправили ссылку для подтверждения.';return}authModal.classList.remove('open');toastMessage(authMode==='signup'?`Добро пожаловать, ${name}!`:'С возвращением!')});

document.head.insertAdjacentHTML('beforeend', `<style>
.support-button{border:1px solid #ffffff1f;background:#ffffff0d;color:#e7e2ff;border-radius:8px;padding:8px 11px;font:600 11px Inter;cursor:pointer;transition:.2s;white-space:nowrap}.support-button:hover{background:#8a6cf622;border-color:#8a6cf677}.support-card{text-align:center}.support-card h2{margin-top:8px}.support-options{display:grid;gap:8px;margin:18px 0}.support-option{padding:12px;border:1px solid var(--line);background:#202126;border-radius:10px;color:#f2f2f4;text-align:left;cursor:pointer;font:600 12px Inter}.support-option span{display:block;color:#93949d;font-weight:400;font-size:10px;margin-top:4px}.support-option:hover{border-color:#8069dd}.support-done{color:#9d8bed!important;font-size:11px!important}
</style>`);
document.querySelector('.header-actions').insertAdjacentHTML('afterbegin','<button class="support-button" id="supportButton">♡ Поддержать</button>');
document.body.insertAdjacentHTML('beforeend', `<div class="auth-modal" id="supportModal" role="dialog" aria-modal="true"><section class="auth-card support-card"><button class="auth-close" id="supportClose">×</button><h2>Поддержать Hikari</h2><p>Ваша поддержка помогает развивать каталог и улучшать просмотр.</p><div class="support-options"><button class="support-option" data-amount="149">149 ₽<span>Небольшая поддержка</span></button><button class="support-option" data-amount="299">299 ₽<span>Поддержка на месяц</span></button><button class="support-option" data-amount="599">599 ₽<span>Большая благодарность</span></button></div><p class="auth-hint">Оплата пока не подключена — это демонстрация интерфейса.</p></section></div>`);
const supportModal=document.querySelector('#supportModal');document.querySelector('#supportButton').onclick=()=>supportModal.classList.add('open');document.querySelector('#supportClose').onclick=()=>supportModal.classList.remove('open');supportModal.addEventListener('click',event=>{if(event.target===supportModal)supportModal.classList.remove('open')});document.querySelectorAll('.support-option').forEach(button=>button.onclick=()=>{const toast=document.querySelector('#toast');toast.textContent=`Спасибо! Поддержка на ${button.dataset.amount} ₽ будет доступна скоро.`;toast.classList.add('show');supportModal.classList.remove('open');setTimeout(()=>toast.classList.remove('show'),2800)});

document.head.insertAdjacentHTML('beforeend', `<style>
.voice-menu{position:absolute;right:57px;bottom:58px;width:214px;padding:7px;background:#18191eeF;border:1px solid #3a3b44;border-radius:11px;box-shadow:0 14px 38px #0008;opacity:0;visibility:hidden;transform:translateY(5px);transition:.18s;z-index:4}.voice-menu.open{opacity:1;visibility:visible;transform:none}.voice-menu-title{color:#8f9099;font-size:10px;font-weight:700;letter-spacing:.5px;padding:7px 8px 6px}.voice-option{border:0;background:transparent;color:#e8e8ec;width:100%;padding:9px 8px;border-radius:7px;text-align:left;font:12px Inter;cursor:pointer;display:flex;align-items:center;justify-content:space-between}.voice-option:hover{background:#ffffff0e}.voice-option.active{background:#8a6cf622;color:#c8bbff}.voice-option span{font-size:10px;color:#91929c}.voice-option.active span{color:#aa98fa}.voice-toggle{min-width:28px}@media(max-width:500px){.voice-menu{right:37px;bottom:49px;width:190px}}
</style>`);
const voiceToggle=document.querySelectorAll('.player-controls .control-label')[2];voiceToggle.classList.add('voice-toggle');voiceToggle.setAttribute('aria-label','Настройки плеера');voiceToggle.title='Настройки плеера';voiceToggle.textContent='⚙';
document.querySelector('#player').insertAdjacentHTML('beforeend', `<div class="voice-menu" id="voiceMenu"><div class="voice-menu-title">ОЗВУЧКА</div><button class="voice-option active" data-voice="РУ">AniLibria <span>Русский</span></button><button class="voice-option" data-voice="РУ">StudioBand <span>Русский</span></button><button class="voice-option" data-voice="JP">Оригинал <span>Японский</span></button><button class="voice-option" data-voice="EN">Dub <span>English</span></button></div>`);
const voiceMenu=document.querySelector('#voiceMenu');voiceToggle.onclick=event=>{event.stopPropagation();voiceMenu.classList.toggle('open')};document.querySelectorAll('.voice-option').forEach(option=>option.onclick=()=>{document.querySelectorAll('.voice-option').forEach(x=>x.classList.remove('active'));option.classList.add('active');voiceMenu.classList.remove('open');const toast=document.querySelector('#toast');toast.textContent=`Озвучка: ${option.firstChild.textContent.trim()}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});document.addEventListener('click',event=>{if(!voiceMenu.contains(event.target)&&event.target!==voiceToggle)voiceMenu.classList.remove('open')});

document.head.insertAdjacentHTML('beforeend', `<style>
.player{border:1px solid #30313a;box-shadow:0 20px 55px #0005}.player-controls{margin:0 13px 12px;padding:10px 12px!important;border:1px solid #ffffff18;border-radius:11px;background:#131419bf;backdrop-filter:blur(12px)}.player-controls button{width:27px;height:27px;border-radius:7px!important;display:grid;place-items:center;color:#e8e8eb!important;transition:background .18s,color .18s}.player-controls button:hover{background:#8a6cf633!important;color:#cfc4ff!important}.player-controls .control-label{width:auto;padding:0 7px;font-size:10px!important;background:#ffffff0b}.timeline{height:4px!important;background:#4a4b53!important}.timeline i{background:#9a82ff!important;box-shadow:0 0 0 1px #a991ff33}.timeline b{background:#d9d0ff!important;box-shadow:0 0 0 3px #8a6cf644}.player:fullscreen{width:100vw;height:100vh;aspect-ratio:auto;border:0;border-radius:0;background:#08090b}.player:fullscreen>img{object-fit:contain}.player:fullscreen .player-controls{bottom:12px}.player:fullscreen .voice-menu{bottom:72px}.fullscreen-button{font-size:19px!important}
</style>`);
const fullscreenButton=document.querySelector('.player-controls button:last-child');fullscreenButton.classList.add('fullscreen-button');fullscreenButton.title='На весь экран';fullscreenButton.setAttribute('aria-label','На весь экран');
fullscreenButton.addEventListener('click', async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('#player').requestFullscreen()}catch{const toast=document.querySelector('#toast');toast.textContent='Полноэкранный режим недоступен';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2000)}});
document.addEventListener('fullscreenchange',()=>{fullscreenButton.textContent=document.fullscreenElement?'⤢':'⛶';fullscreenButton.title=document.fullscreenElement?'Выйти из полного экрана':'На весь экран'});
document.head.insertAdjacentHTML('beforeend', `<style>.auth-switch{display:block;width:100%;border:0;background:none;color:#aa98fa;font:12px Inter;padding:13px 0 0;cursor:pointer}.auth-switch:hover{text-decoration:underline}.auth-card .primary:disabled{opacity:.6;cursor:wait}.auth-hint:empty{display:none}.auth-hint:not(:empty){color:#ffaaa6!important;margin-top:10px!important}.profile.has-avatar{padding:0;overflow:hidden}.profile.has-avatar img{width:100%;height:100%;object-fit:cover}.profile-card{position:relative}.profile-avatar-editor{width:82px;height:82px;margin:0 auto 16px;border-radius:50%;background:#282a31;border:1px solid #42434c;display:grid;place-items:center;overflow:hidden;color:#c7bdff;font:700 24px Manrope;cursor:pointer}.profile-avatar-editor img{width:100%;height:100%;object-fit:cover}.profile-avatar-editor:hover:after{content:'Изменить';position:absolute;inset:0;display:grid;place-items:center;background:#0c0d10aa;color:#fff;font:10px Inter}.profile-card textarea{resize:vertical;min-height:72px;width:100%;background:#202126;border:1px solid #32333b;border-radius:9px;padding:11px;color:#fff;outline:none;font:13px Inter}.profile-card textarea:focus{border-color:#8069dd}.logout-button{width:100%;margin-top:10px;background:transparent;color:#b7b8c0;border:1px solid #393a43;border-radius:9px;padding:10px;font:12px Inter;cursor:pointer}.logout-button:hover{border-color:#8f6268;color:#ffaeb2}</style>`);
document.body.insertAdjacentHTML('beforeend', `<div class="auth-modal" id="profileModal" role="dialog" aria-modal="true"><form class="auth-card profile-card" id="profileForm"><button type="button" class="auth-close" id="profileClose">×</button><label class="profile-avatar-editor" for="profileAvatar" id="avatarPreview">?</label><input id="profileAvatar" type="file" accept="image/png,image/jpeg,image/webp" hidden><h2>Ваш профиль</h2><p id="profileEmail">—</p><label for="profileName">Имя</label><input id="profileName" required maxlength="24" placeholder="Ваше имя"><label for="profileBio">О себе</label><textarea id="profileBio" maxlength="180" placeholder="Расскажите немного о себе"></textarea><p id="profileError" class="auth-hint" aria-live="polite"></p><button class="primary" type="submit" id="profileSave">Сохранить изменения</button><button class="logout-button" type="button" id="logoutButton">Выйти из аккаунта</button></form></div>`);
const profileModal=document.querySelector('#profileModal'),profileAvatarInput=document.querySelector('#profileAvatar'),avatarPreview=document.querySelector('#avatarPreview');let pendingAvatar='';
function fillProfile(user){const meta=user?.user_metadata||{},name=meta.name||user?.email?.split('@')[0]||'';document.querySelector('#profileEmail').textContent=user?.email||'';document.querySelector('#profileName').value=name;document.querySelector('#profileBio').value=meta.bio||'';pendingAvatar=meta.avatar||'';avatarPreview.innerHTML=pendingAvatar?`<img src="${pendingAvatar}" alt="${name}">`:name.slice(0,1).toUpperCase()||'?';document.querySelector('#profileError').textContent=''}
function resizeAvatar(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas'),size=160;canvas.width=size;canvas.height=size;const context=canvas.getContext('2d'),scale=Math.max(size/image.width,size/image.height),width=image.width*scale,height=image.height*scale;context.drawImage(image,(size-width)/2,(size-height)/2,width,height);resolve(canvas.toDataURL('image/webp',.82))};image.onerror=reject;image.src=reader.result};reader.readAsDataURL(file)})}
profileAvatarInput.addEventListener('change',async()=>{const file=profileAvatarInput.files[0];if(!file)return;if(file.size>5*1024*1024){document.querySelector('#profileError').textContent='Выберите изображение до 5 МБ.';return}try{pendingAvatar=await resizeAvatar(file);avatarPreview.innerHTML=`<img src="${pendingAvatar}" alt="Новый аватар">`}catch{document.querySelector('#profileError').textContent='Не удалось обработать изображение.'}});
document.querySelector('#profileClose').onclick=()=>profileModal.classList.remove('open');profileModal.addEventListener('click',event=>{if(event.target===profileModal)profileModal.classList.remove('open')});document.querySelector('#profileForm').addEventListener('submit',async event=>{event.preventDefault();const name=document.querySelector('#profileName').value.trim(),bio=document.querySelector('#profileBio').value.trim(),errorBox=document.querySelector('#profileError'),save=document.querySelector('#profileSave');errorBox.textContent='';save.disabled=true;save.textContent='Сохраняем…';const {data,error}=await authClient.auth.updateUser({data:{name,bio,avatar:pendingAvatar}});save.disabled=false;save.textContent='Сохранить изменения';if(error){errorBox.textContent=error.message;return}setProfile(data.user);profileModal.classList.remove('open');toastMessage('Профиль обновлён')});document.querySelector('#logoutButton').onclick=async()=>{await authClient.auth.signOut();profileModal.classList.remove('open');toastMessage('Вы вышли из аккаунтa')};

document.head.insertAdjacentHTML('beforeend', `<style>
.profile-view{max-width:740px;padding-top:46px;padding-bottom:75px}.profile-back{margin-bottom:22px}.profile-page-card{background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:30px;display:grid;grid-template-columns:150px 1fr;gap:34px}.profile-page-avatar{width:128px;height:128px;border:1px solid #494a54;border-radius:50%;display:grid;place-items:center;overflow:hidden;background:#272831;color:#beb1ff;font:800 38px Manrope;cursor:pointer;position:relative}.profile-page-avatar img{width:100%;height:100%;object-fit:cover}.profile-page-avatar:hover:after{content:'Сменить фото';position:absolute;inset:0;display:grid;place-items:center;background:#101115b8;color:#fff;font:11px Inter}.profile-page-main h1{font:700 29px Manrope;margin:0 0 4px}.profile-page-email{margin:0 0 23px;color:#93949e;font-size:12px}.profile-page-main label{display:block;margin:13px 0 6px;color:#cbccd1;font-size:11px}.profile-page-main input,.profile-page-main textarea{width:100%;background:#202126;border:1px solid #353640;border-radius:9px;padding:11px;color:#fff;outline:none;font:13px Inter}.profile-page-main textarea{min-height:85px;resize:vertical}.profile-page-main input:focus,.profile-page-main textarea:focus{border-color:#8069dd}.profile-actions{display:flex;gap:9px;margin-top:20px}.profile-actions .logout-button{width:auto;margin:0;padding:0 13px}@media(max-width:600px){.profile-page-card{grid-template-columns:1fr;padding:22px;gap:20px}.profile-page-avatar{margin:auto}.profile-view{padding-top:28px}}
</style>`);
document.querySelector('main').insertAdjacentHTML('beforeend', `<section class="view" id="profile"><div class="content profile-view"><button class="back-link profile-back" data-view="home">← На главную</button><div class="profile-page-card"><div><label class="profile-page-avatar" for="profilePageAvatar" id="profilePageAvatarPreview">?</label><input id="profilePageAvatar" type="file" accept="image/png,image/jpeg,image/webp" hidden></div><form class="profile-page-main" id="profilePageForm"><h1>Мой профиль</h1><p class="profile-page-email" id="profilePageEmail">—</p><label for="profilePageName">Имя</label><input id="profilePageName" required maxlength="24" placeholder="Ваше имя"><label for="profilePageBio">О себе</label><textarea id="profilePageBio" maxlength="180" placeholder="Расскажите немного о себе"></textarea><p id="profilePageError" class="auth-hint" aria-live="polite"></p><div class="profile-actions"><button class="primary" id="profilePageSave" type="submit">Сохранить</button><button class="logout-button" id="profilePageLogout" type="button">Выйти</button></div></form></div></div></section>`);
const profilePageAvatarInput=document.querySelector('#profilePageAvatar'),profilePageAvatarPreview=document.querySelector('#profilePageAvatarPreview');let pendingPageAvatar='';
function fillProfilePage(user){const meta=user?.user_metadata||{},name=meta.name||user?.email?.split('@')[0]||'',avatarElement=document.querySelector('#profilePageAvatarPreview');document.querySelector('#profilePageEmail').textContent=user?.email||'';document.querySelector('#profilePageName').value=name;document.querySelector('#profilePageBio').value=meta.bio||'';pendingPageAvatar=meta.avatar||'';avatarElement.innerHTML=pendingPageAvatar?`<img src="${pendingPageAvatar}" alt="${name}">`:name.slice(0,1).toUpperCase()||'?';document.querySelector('#profilePageError').textContent=''}
profilePageAvatarInput.addEventListener('change',async()=>{const file=profilePageAvatarInput.files[0];if(!file)return;if(file.size>5*1024*1024){document.querySelector('#profilePageError').textContent='Выберите изображение до 5 МБ.';return}try{pendingPageAvatar=await resizeAvatar(file);profilePageAvatarPreview.innerHTML=`<img src="${pendingPageAvatar}" alt="Новый аватар">`}catch{document.querySelector('#profilePageError').textContent='Не удалось обработать изображение.'}});
document.querySelector('#profilePageForm').addEventListener('submit',async event=>{event.preventDefault();const name=document.querySelector('#profilePageName').value.trim(),bio=document.querySelector('#profilePageBio').value.trim(),errorBox=document.querySelector('#profilePageError'),save=document.querySelector('#profilePageSave');errorBox.textContent='';save.disabled=true;save.textContent='Сохраняем…';const {data,error}=await authClient.auth.updateUser({data:{name,bio,avatar:pendingPageAvatar}});save.disabled=false;save.textContent='Сохранить';if(error){errorBox.textContent=error.message;return}setProfile(data.user);toastMessage('Профиль обновлён')});document.querySelector('#profilePageLogout').onclick=async()=>{await authClient.auth.signOut();setView('home');toastMessage('Вы вышли из аккаунта')};

document.head.insertAdjacentHTML('beforeend', `<style>
.profile-side{display:flex;flex-direction:column;align-items:center;gap:9px}.profile-side .profile-page-avatar{width:94px;height:94px;font-size:30px;margin-bottom:7px}.profile-side-nav{width:100%;display:grid;gap:5px}.profile-side-nav button{border:0;background:transparent;color:#a9aab2;border-radius:8px;padding:9px 10px;text-align:left;font:12px Inter;cursor:pointer}.profile-side-nav button:hover,.profile-side-nav button.active{background:#8a6cf61c;color:#d0c5ff}.profile-side-nav button[disabled]{opacity:.45;cursor:not-allowed}.profile-activity{display:none;grid-column:2}.profile-activity.active{display:block}.profile-activity h1{font:700 29px Manrope;margin:0 0 5px}.profile-activity>p{color:#94959e;font-size:12px;margin:0 0 20px}.watched-list{display:grid;gap:8px}.watched-item{display:flex;align-items:center;gap:11px;padding:9px;border:1px solid var(--line);border-radius:10px;background:#1a1b20}.watched-item img{width:42px;height:55px;border-radius:6px;object-fit:cover}.watched-item b{font-size:12px}.watched-item span{display:block;margin-top:4px;color:#9697a0;font-size:11px}.watched-item i{margin-left:auto;color:#aa98fa;font-style:normal;font-size:11px}@media(max-width:600px){.profile-side{align-items:stretch}.profile-side .profile-page-avatar{margin:auto}.profile-side-nav{grid-template-columns:repeat(3,1fr)}.profile-side-nav button{text-align:center;padding:8px 3px;font-size:10px}.profile-activity{grid-column:1}.profile-page-card:has(.profile-activity.active) .profile-side{display:none}}
</style>`);
const profileSide=document.querySelector('.profile-page-card>div:first-child');profileSide.className='profile-side';profileSide.innerHTML=`<label class="profile-page-avatar" for="profilePageAvatar" id="profilePageAvatarPreview">?</label><input id="profilePageAvatar" type="file" accept="image/png,image/jpeg,image/webp" hidden><nav class="profile-side-nav"><button class="active" data-profile-tab="account">Профиль</button><button data-profile-tab="watched">Просмотрено</button><button disabled title="Скоро будет доступно">Друзья · скоро</button></nav>`;
document.querySelector('.profile-page-main').insertAdjacentHTML('afterend', `<section class="profile-activity" id="profileActivity"><h1>Просмотрено</h1><p>Ваша недавняя история просмотра.</p><div class="watched-list">${shows.slice(0,4).map((show,index)=>`<article class="watched-item"><img src="${show[3]}" alt="${show[0]}"><div><b>${show[0]}</b><span>${index===0?'08 серия · 14:32':show[1]}</span></div><i>Продолжить →</i></article>`).join('')}</div></section>`);
document.querySelectorAll('[data-profile-tab]').forEach(button=>button.onclick=()=>{const watched=button.dataset.profileTab==='watched';document.querySelector('.profile-page-main').style.display=watched?'none':'block';document.querySelector('#profileActivity').classList.toggle('active',watched);document.querySelectorAll('[data-profile-tab]').forEach(x=>x.classList.toggle('active',x===button))});
document.querySelector('#profilePageAvatar').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){document.querySelector('#profilePageError').textContent='Выберите изображение до 5 МБ.';return}try{pendingPageAvatar=await resizeAvatar(file);document.querySelector('#profilePageAvatarPreview').innerHTML=`<img src="${pendingPageAvatar}" alt="Новый аватар">`}catch{document.querySelector('#profilePageError').textContent='Не удалось обработать изображение.'}});
